### ISSUE TITLE
Arrayf.C() optimization

### ISSUE THREAD

**Issue by sbinet** [Kunde21/numgo#1]
hi,

perusing the code, I just saw:

https://github.com/Kunde21/numgo/blob/master/accessors.go#L25

``` go
b = create(a.shape...)
for i, v := range a.data {
    b.data[i] = v
}
```

If I am not mistaken, it should probably just read:

``` go
b = create(a.shape...)
copy(b.data, a.data)
```

this should compile to a straightforward memcopy, instead of the many bound checks of the first version.

**Comment by Kunde21** [comment]
You're right. 

Updated.
