### ISSUE TITLE
Code reorganisation and file naming

### ISSUE THREAD

**Issue by pinpox** [Kunde21/numgo#11]
After issue #8 I though this might be a point to bring up.

How would you go about the naming of the files and distributing the code in them? I suppose the "general" stuff that applies to any array type would go into numgo.go. For the Arrayb-specific methods we have bool.go. Where would you like the Array64-specific code?

It might be clearer to just have

- numgo.go: General stuff applying to any array type
- array64.go: A new file that holds Array64-specific code
- arrayb.go: bool.go renamed, containing Arrayb-specific code.

Just an idea, I'm open for any other suggestions

**Comment by Kunde21** [comment]
Sound good.  We could use nDim.go instead of numgo.go so users don't expect anything special in the file named the same as the package.  

This can be incorporated into #10 easily.
