### ISSUE TITLE
Shape() should return a int

### ISSUE THREAD

**Issue by pinpox** [Kunde21/numgo#3]
Hi,

All other methods work with ints, only Shape() returns a []uint64 which makes it unnessesary complicated to use.

Consider this code:

```go
rows := myArr.Shape()[0]
collums :=myArr.Shape()[1]
depth :=myArr.Shape()[2]
newArr := numgo.NewArray64(nil,rows,collums,depth) //ERROR
```

It throws an error because NewArray64 expects ints, and Shape returns uint64. 
To avoid using casts to int all the time, wouldn't it be easier if Shape just returns int so that it is directly compatible with the other functions?

If interested I would submit a pull request.
Let me know what you think!

Pablo

**Comment by Kunde21** [comment]
This sounds very useful.  I'll review the PR code.
